markdown: kramdown

latest-server: 1.4.1
latest-demo-server: 1.4.1
latest-data-access-api: 1.2.0
latest-sql-provider: 1.4.1
latest-sample-data-impl: 0.0.2

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      category: "Documentation"

